name: 5-final-project-spring-2024-namelessssss
services:
  - name: web-app
    image:
      registry_type: DOCKER_HUB
      repository: jiahualiao/web-app
      tag: latest
    instance_count: 1
    instance_size_slug: basic-s
    routes:
      - path: /

  - name: weather-data-collect
    image:
      registry_type: DOCKER_HUB
      repository: jiahualiao/weather-data-collect
      tag: latest
    instance_count: 1
    instance_size_slug: basic-s
