name: weather-checking-app
services:
  - name: web
    github:
      branch: main
      repo_clone_url: https://github.com/software-students-spring2024/5-final-project-spring-2024-namelessssss.git
      deploy_on_push: true
    dockerfile_path: web-app/Dockerfile
    source_dir: web-app
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /

  - name: weather-data
    github:
      branch: main
      repo_clone_url: https://github.com/software-students-spring2024/5-final-project-spring-2024-namelessssss.git
      deploy_on_push: true
    dockerfile_path: weather-data-collect/Dockerfile
    source_dir: weather-data-collect
    instance_count: 1
    instance_size_slug: basic-xxs