name: webApp
region: nyc
services:
  - name: web-app
    image:
      registry_type: DOCKER_HUB
      repository: kalados/web-app
      tag: latest
    environment_slug: python
    http_port: 5050
    instance_count: 1
    instance_size_slug: basic-s
    routes:
      - path: /

envs:
  - key: MONGODB_URI
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
    value: mongodb+srv://nameless.wun5lpq.mongodb.net/?authSource=%24external&authMechanism=MONGODB-X509&retryWrites=true&w=majority&appName=Nameless

  - key: DB_NAME
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
    value: Project5

  - key: DB_COLLECTION_NAME
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
    value: WeatherData

  - key: SSL_CERT_FILE
    scope: RUN_AND_BUILD_TIME
    type: GENERAL
    value: X509-cert-4588623656805667932.pem
