name: Fetch Weather CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Test Weather Data Collection
        run: |
          cd weather-data-collect
          docker build -t weather-data-collect .
          docker run --rm weather-data-collect python -m unittest discover tests

  push-to-docker-hub:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check if secrets are empty
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "One of the secrets is empty!"
          else
            echo "Secrets are not empty."
          fi

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Weather Data Collection to Docker Hub
        run: |
          cd weather-data-collect
          docker build -t weather-data-collect .
          docker tag weather-data-collect ${{ secrets.DOCKER_USERNAME }}/weather-data-collect:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/weather-data-collect:latest

  deploy:
    needs: push-to-docker-hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to DigitalOcean
        env:
          DIGITALOCEAN_CLI_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          sudo snap install doctl
          doctl auth init --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          doctl apps list --format ID,Created
          #doctl apps update 4cc7d717-3d4a-49e3-ab40-581b02fe6061 --spec weather-data-collect/weather-data-collect.yaml